CREATE TABLE IF NOT EXISTS dim_city(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Name VARCHAR(50),
    country VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS dim_time(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    datetime  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    hour INT,
    day INT,
    month INT,
    year INT
);
CREATE TABLE IF NOT EXISTS fact_weather(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    temperature float,
    feels_like float,
    pressure int,
    humidity int,
    cloud int,
    wind_speed float,
    aqi int,
    city_id int NOT NULL,
    time_id int NOT NULL,
    Constraint fk_city_weather
    FOREIGN key (city_id)
    REFERENCES dim_city(id),
    Constraint fk_time_weather
    FOREIGN key (time_id)
    REFERENCES dim_time(id)
);

CREATE TABLE IF NOT EXISTS runs(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    last_run TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS raw_air_quality(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city_id int NOT NULL,
    data JSONB,
    insert_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_city_air 
    FOREIGN KEY(city_id)
    REFERENCES dim_city(id)
);
CREATE TABLE IF NOT EXISTS raw_weather(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city_id int NOT NULL,
    data JSONB,
    insert_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_city_air 
    FOREIGN KEY(city_id)
    REFERENCES dim_city(id)
);
INSERT INTO dim_city (name, country) VALUES 
('Paris', 'FR'),
('Marseille', 'FR'),
('Lyon', 'FR'),
('Toulouse', 'FR'),
('Nice', 'FR'),
('Nantes', 'FR'),
('Strasbourg', 'FR'),
('Montpellier', 'FR'),
('Bordeaux', 'FR'),
('Lille', 'FR');

INSERT INTO runs (last_run) VALUES 
(CURRENT_TIMESTAMP);